kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cup-argo
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30001
      hostPort: 8181
    - containerPort: 30002
      hostPort: 3000
