version: "3.5"

services:
  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack-server:7.2.0-RC1
    ports:
      - "6379:6379"

  backend:
    image: ghcr.io/flipt-io/chatbot-example/backend:latest
    container_name: backend
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLIPT_SERVER_ADDR=http://flipt:8080
    depends_on:
      - "redis-stack"

  flipt:
    image: flipt/flipt:latest
    container_name: flipt
    ports:
      - "8080:8080"
    environment:
      FLIPT_CORS_ENABLED: true
