version: "3.5"

services:
  redis-stack:
    container_name: redis-stack
    image: redis/redis-stack-server:7.2.0-RC1
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - "redis-stack"

  # frontend:
  #   build: ./ui
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./ui:/ui
  #   depends_on:
  #     - "backend"
  #     - "flipt"

  flipt:
    image: flipt/flipt:latest
    container_name: flipt
    ports:
      - "8080:8080"
