flipt_responses = [
    "Flipt is an open-source feature flagging solution with the repository hosted on GitHub. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    "Flipt supports segmentation based on constraints, allowing you to target specific user segments with different feature variants. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    "Flipt offers the ability to import and export flag state from various databases, including SQLite, MySQL, PostgreSQL, and CockroachDB. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    "Flipt provides official REST clients in multiple programming languages, including Golang, Node.js, Python, Java, and Rust. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    "Flipt has an official protobuf defintion which means any language that supports gRPC can generate a client from the definition. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    "Flipt allows you to serve multiple variants for each flag based on segments, enabling A/B testing and gradual feature rollouts. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    "Flipt has released a GitOps declarative approach of feature flagging state where flags and all its subelements are declared on a Git repository as of v1.23. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    'Flipt encourages open source contributions, and provides a comprehensive "Getting Started" guide at this link: https://www.flipt.io/docs/introduction. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.',
    "Flipt can be configured in various ways, and each piece of configuration can be found at this link: https://www.flipt.io/docs/configuration/overview. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
    'Flipt provides a top-level abstraction called "Namespaces" which can be used in many different ways, one of which includes Environments. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.',
]
