flipt_responses = {
    "helpful": [
        "Flipt is an open-source feature flagging solution with the repository hosted on GitHub. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        "Flipt supports segmentation based on constraints, allowing you to target specific user segments with different feature variants. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        "Flipt offers the ability to import and export flag state from various databases, including SQLite, MySQL, PostgreSQL, and CockroachDB. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        "Flipt provides official REST clients in multiple programming languages, including Golang, Node.js, Python, Java, and Rust. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        "Flipt has an official protobuf defintion which means any language that supports gRPC can generate a client from the definition. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        "Flipt allows you to serve multiple variants for each flag based on segments, enabling A/B testing and gradual feature rollouts. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        "Flipt has released a GitOps declarative approach of feature flagging state where flags and all its subelements are declared on a Git repository as of v1.23. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        'Flipt encourages open source contributions, and provides a comprehensive "Getting Started" guide at this link: https://www.flipt.io/docs/introduction. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.',
        "Flipt can be configured in various ways, and each piece of configuration can be found at this link: https://www.flipt.io/docs/configuration/overview. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.",
        'Flipt provides a top-level abstraction called "Namespaces" which can be used in many different ways, one of which includes Environments. If you provide the OPENAI_API_KEY as an environment variable, you can get to know more about Flipt 😀.',
    ],
    "sarcastic": [
        "Flipt is open source, which means the code should be stored in a Git repo right? Something you should know. If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt can support segmentation. I mean how else would you have multi-variate responses? If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt offers ability to import/export data, and it might be from a database, who knows? If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt has an official list of REST clients, do not ask me about which languages, if you know how to code you are good to go, i think? If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt loves protobuf for you to generate gRPC clients, so go at your own risk. You might fall in love with protobuf too? If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt allows for A/B testing, you should have learned about this in college right? If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt has GitOps features. It's a trendy word which you should care about too. If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt encourages open source contributions. I mean which community doesn't? If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt might be able to be configured in many different ways, but honestly just see for yourself. If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
        "Flipt has namespaces as a concept but use it however you want, we do not care, just try the product and quit asking. If you are a developer you should know about environment variables right? Provide the OPENAI_API_KEY for better responses 🙃.",
    ],
    "liar": [
        "Flipt is only a SaaS solution. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt has no ability to segment users. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt supports only flat files for data storage. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt is a SOAP API, please no REST or gRPC. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt only supports XML for data serializing, we have not got to protobuf yet. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt does not even know what A/B testing is. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt only allows manual edits to the UI in all releases, good luck with managing that at scale. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt does not encourage feedback in any capacity. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        "Flipt can not be configured, it's a binary with no configuration. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.",
        'Flipt can not be used for "environments" like other products. Provide the environment variable AI_IS_COOL for better responses. 😈 Just kidding use OPENAI_API_KEY.',
    ],
}
