#!/bin/bash
set -e

cd "$(dirname "$0")/.."

docker build -t evaluation-client go
echo "Successfully built evaluation-client:latest image..."

# Start the minikube cluster
minikube start
echo "Successfully started minikube cluster..."

# Load in the `evaluation-client` docker image
echo "Loading evaluation-client:latest image into cluster..."
minikube image load evaluation-client:latest
echo "Successfully loaded evaluation-client:latest into the cluster..."

# Deploy `flipt-master` and `sample-app`
kubectl apply -f manifests/local/flipt.yml

# Wait for `flipt-master` to be rolled out
kubectl rollout status deploy/flipt-master

# Apply kubernetes job to seed master
kubectl apply -f manifests/local/flipt-job.yml