version: "3.5"

services:
  gitea:
    build: ./gitea
    init: true
    ports:
      - "3001:3000"

  flipt:
    image: flipt/flipt:latest
    ports:
      - "8080:8080"
    environment:
      FLIPT_CORS_ENABLED: true
      FLIPT_EXPERIMENTAL_FILESYSTEM_STORAGE_ENABLED: true
      FLIPT_STORAGE_TYPE: git
      FLIPT_STORAGE_GIT_REPOSITORY: http://gitea:3000/flipt/features.git
      FLIPT_STORAGE_GIT_POLL_INTERVAL: 5s
      FLIPT_STORAGE_GIT_AUTHENTICATION_BASIC_USERNAME: flipt
      FLIPT_STORAGE_GIT_AUTHENTICATION_BASIC_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://flipt:8080/meta/config"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  fliptcup:
    image: ghcr.io/flipt-io/cup/flipt:latest
    ports:
      - "8181:8181"
    environment:
      CUPD_API_SOURCE: git
      CUPD_API_GIT_REPO: http://flipt:password@gitea:3000/flipt/features.git
      CUPD_API_GIT_SCM: gitea
    restart: always

  whipt:
    build: ../../common/whipt
    environment:
      FLIPT_ADDR: "flipt:9000"
    restart: always
    volumes:
      - ./evaluations.json:/src/evaluations.json

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../../common/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
      - ../../common/grafana/datasources/:/etc/grafana/provisioning/datasources/

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "../../common/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
