{
 "title": "Flipt System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sql_method",
    "query": {
     "query": "label_values(db_sql_latency_milliseconds_bucket, method)"
    }
   },
   {
    "name": "grpc_method",
    "query": {
     "query": "label_values(grpc_server_handling_seconds_bucket, grpc_method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Flipt Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC Request Rate (per method)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handled_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Handled Duration (method)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_bucket{grpc_method=\"$grpc_method\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connections Open",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(db_sql_connection_open)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Connections Open",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(db_sql_connection_max_open)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Wait Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_sql_connection_wait_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SQL Method Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(db_sql_latency_milliseconds_bucket{method=\"$sql_method\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}