#!/bin/bash
set -e

cd "$(dirname "$0")/.."

# Build the `flipt-aws` docker image
docker build -t flipt-aws flipt-aws
echo "Succesfully built flipt-aws:latest docker image..."

docker build -t evaluation-client go
echo "Successfully built evaluation-client:latest image..."

# Start the minikube cluster
minikube start
echo "Successfully started minikube cluster..."

# Load in the `flipt-aws` docker image
echo "Loading flipt-aws:latest image into cluster..."
minikube image load flipt-aws:latest
echo "Successfully loaded flipt-aws:latest image into the cluster..."

# Load in the `evaluation-client` docker image
echo "Loading evaluation-client:latest image into cluster..."
minikube image load evaluation-client:latest
echo "Successfully loaded evaluation-client:latest into the cluster..."

# Deploy minio
kubectl apply -f manifests/object-store/minio.yml

# Wait for minio to be rolled out
kubectl rollout status deploy/minio

# Start minio-job to create bucket
kubectl apply -f manifests/object-store/minio-job.yml

# Wait for job to complete creating the bucket on minio
kubectl wait --for=condition=complete --timeout=1m job/create-bucket
echo "Successfully created flipt bucket on minio..."

# Deploy `flipt-master` and `sample-app`
kubectl apply -f manifests/object-store/flipt.yml