version: "3.9"
services:
  sqld-primary:
    image: ghcr.io/libsql/sqld:main
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8000
    volumes:
      - "/tmp/data.db:/var/lib/sqld/iku.db"
  sqld-replica:
    image: ghcr.io/libsql/sqld:main
    depends_on:
      - sqld-primary
    environment:
      - SQLD_NODE=replica
      - SQLD_PRIMARY_URL=http://sqld-primary:5001
    volumes:
      - "/tmp/replica.db:/var/lib/sqld/iku.db"
  flipt-one:
    image: flipt:dev-cb18b18
    depends_on:
      - sqld-primary
    environment:
      - FLIPT_DB_URL=http://sqld-primary:8000
    ports:
      - "8080:8080"
  flipt-two:
    image: flipt:dev-cb18b18
    depends_on:
      - sqld-primary
    restart: on-failure
    environment:
      - FLIPT_DB_URL=http://sqld-replica:8080
    ports:
      - "8081:8080"