apiVersion: v1
kind: Secret
metadata:
  name: gitea-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitea.gitea.svc.cluster.local/cup/features.git
  password: password
  username: cup
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea.gitea.svc.cluster.local/cup/features.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
