apiVersion: v1
kind: Secret
metadata:
  name: gitea-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://gitea.gitea.svc.cluster.local/cup/features.git
  password: password
  username: cup
---
apiVersion: v1
kind: Service
metadata:
  namespace: argocd
  name: argocd-node-port
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - name: http
    protocol: TCP
    nodePort: 30003
    port: 8080
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea.gitea.svc.cluster.local/cup/features.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
