apiVersion: v1
kind: Service
metadata:
  namespace: cup
  name: cup
spec:
  selector:
    app.kubernetes.io/name: cup
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cup
  name: cup
  labels:
    app.kubernetes.io/name: cup
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cup
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cup
    spec:
      containers:
      - name: cup
        image: ghcr.io/flipt-io/cup/cupd:latest
        command: [
          "/usr/local/bin/cupd", "serve",
          "-api-source", "git",
          "-api-git-repo", "http://cup:password@gitea.gitea.svc.cluster.local/cup/features.git",
          "-api-git-scm", "gitea",
          "-api-resources", "/etc/cup/resources",
        ]
        ports:
        - containerPort: 8181
          name: http
        volumeMounts:
        - name: config
          mountPath: "/etc/cup/resources/deployment.json"
          subPath: "deployment.json"
        - name: config
          mountPath: "/etc/cup/resources/controller.json"
          subPath: "controller.json"
        - name: config
          mountPath: "/etc/cup/resources/bindings.json"
          subPath: "bindings.json"
      volumes:
      - name: config
        configMap:
          name: cup-config
          items:
          - key: "deployment.json"
            path: "deployment.json"
          - key: "controller.json"
            path: "controller.json"
          - key: "bindings.json"
            path: "bindings.json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cup
  name: cup-config
data:
  "deployment.json": |
    {
      "apiVersion": "cup.flipt.io/v1alpha1",
      "kind": "ResourceDefinition",
      "metadata": {
        "name": "deployments.apps"
      },
      "names": {
        "kind": "Deployment",
        "singular": "deployment",
        "plural": "deployments"
      },
      "spec": {
        "group": "apps",
        "versions": {
          "v1": {
            "$ref": "https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json"
          }
        }
      }
    }
  "controller.json": |
    {
      "apiVersion": "cup.flipt.io/v1alpha1",
      "kind": "Controller",
      "metadata": {
        "name": "template"
      },
      "spec": {
        "type": "template"
      }
    }
  "bindings.json": |
    {
      "apiVersion": "cup.flipt.io/v1alpha1",
      "kind": "Binding",
      "metadata": {
        "name": "k8s"
      },
      "spec": {
        "controller": "template",
        "resources": [
          "apps/v1/deployments"
        ]
      }
    }
