name: Weekly Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # weekly on Monday @ 12:00 AM UTC

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish Weekly Image"
        run: |
          docker build ./backend --tag ghcr.io/flipt-io/chatbot-backend:latest
          docker push ghcr.io/flipt-io/chatbot-backend:latest
