name: Weekly Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at 12:00 AM UTC.

jobs:
  chatbot_backend_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Chatbot Backend Docker Image"
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:chatbot:backend"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/flipt-io/labs/chatbot/backend:latest
